base:
  project: aissm_mlops
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance-data.csv

split_data:
  train_path: data/processed/train.csv
  test_path: data/processed/test.csv
  test_size: 0.2

estimators:
  RandomForest:
    params:
      n_estimators: 100
      max_depth: 4

model_path: models/models.joblib

reports:
   params: reports/params.json
   score: reports/scores.json

mlflow_config:
  artifact_dir: artifacts
  experiment_name: insurance_aissms
  run_name: mlops
  registered_model_name: RandomForest
  remote_server_uri: http://127.0.0.1:5000