name: Build, Analyze, Scan
on: 
    push:
        branches:
            - main

jobs:
    build_analyze_scan:
        name: Build
        runs-on: ubuntu-latest    #[self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                  python-version: 3.11

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            